title: 'stainedby'
project: 'stainedby'
telephone: (+82)10-7581-1003
email: stainedby8363@gmail.com
address: 20-5, Dogok-ro 3-gil, Gangnam-gu, Seoul
description: stainedby
baseurl: ''
url: 'https://bonta7.github.io'
repository: bonta7/bonta7.github.io
exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock  
  - README.md  
image: 'assets/images/banner01.jpg'
avatar: 'assets/images/banner01.jpg'
slides:
  - assets/images/slides01.png
facebook:
twitter:
instagram:  
about:
  left: 그 것이 존재하던, 존재하지 않던<br />현재에 고정하여 아름다운 결과물을 만들어 냅니다.
  center: 우리는 공간에 남는 시간의 자극에 주목합니다.
  right: 당신이 원하는 시간과 공간을 연출합니다.
services:
  title: 흔적에 대한 기록.
  subtitle: 스테인드 바이는 소중한 순간을 기록합니다.<br />상상으로 담아놓은 미디어 콘텐츠를 모두 기록합니다.
  items:
    - COMMERCIAL FILM
    - VIRAL FILM
    - FASHION FILM
    - MUSIC VIDEO
    - MOVIE
    - VR
    - DRONE
    - SOUND PRODUCT
portfolio-item:
  - image: https://img.youtube.com/vi/geYruQsxbQg/hqdefault.jpg
    link: https://youtu.be/geYruQsxbQg
    
  - image: https://img.youtube.com/vi/_Gkbt5QBBm0/hqdefault.jpg
    link: https://youtu.be/_Gkbt5QBBm0    
    
  - image: https://img.youtube.com/vi/_QyP-MRnz1k/hqdefault.jpg
    link: https://youtu.be/_QyP-MRnz1k
    
  - image: https://img.youtube.com/vi/y_wZ2S5An0w/hqdefault.jpg
    link: https://youtu.be/y_wZ2S5An0w
    
  - image: https://img.youtube.com/vi/SCey8uTs6zY/hqdefault.jpg
    link: https://youtu.be/SCey8uTs6zY
    
  - image: https://img.youtube.com/vi/koPZwMhft7k/hqdefault.jpg
    link: https://youtu.be/koPZwMhft7k
sass:
  style: compressed
  load_paths:
    - _sass
