title: 'stainedby'
project: 'stainedby'
telephone: (+82)10-7581-1003
email: stainedby8363@gmail.com
description: stainedby
baseurl: ''
url: 'https://bonta7.github.io'
repository: bonta7/bonta7.github.io
exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock  
  - README.md  
image: 'assets/images/banner01.jpg'
avatar: 'assets/images/banner01.jpg'
slides:
  - assets/images/slides01.png
facebook:
twitter:
instagram:  
about:
  left: 그 것이 존재하던, 존재하지 않던<br />현재에 고정하여 아름다운 결과물을 만들어 냅니다.
  center: 우리는 공간에 남는 시간의 자극에 주목합니다.
  right: 당신이 원하는 시간과 공간을 연출합니다.
services:
  title: 흔적에 대한 기록.
  subtitle: 스테인드 바이는 소중한 순간을 기록합니다.<br />상상으로 담아놓은 미디어 콘텐츠를 모두 기록합니다.
  items:
    - COMMERCIAL FILM
    - VIRAL FILM
    - FASHION FILM
    - MUSIC VIDEO
    - MOVIE
    - VR
    - DRONE
    - SOUND PRODUCT
portfolio: |
  This is a multi-line string.  
  "special" metacharacters may  
  appear here. The extent of this string is  
  indicated by indentation.   
portfolio-item:
  - image: assets/images/SK_Live_200901.JPG
    link: https://mall.saucelive.net/broadcast/10771?sessionKey=3N0JMQP8z3dB/vwaLUV6nXIrX70dBDOTAUedIrNr+YG0KqpTVmCgKFXngS0Z09P8UEVgjQeQIjXXpOloF09CurpNStsPHOSLd7RCsh2WggjLWhc2664QxMTULpnA/l+0bl/+2QZIeJATz5rKp9CorKDTST0uN4NSZaadnTkwnWVatZx+zCzXUR3mOTJx9nfU&serviceId=skmagic
    
  - image: https://img.youtube.com/vi/fz50p2FZo0c/hqdefault.jpg
    link: https://youtu.be/fz50p2FZo0c
    
  - image: https://img.youtube.com/vi/A3AURx-aYj8/hqdefault.jpg
    link: https://youtu.be/A3AURx-aYj8     
    
  - image: assets/images/SK_live_show_0819.JPG
    link: https://mall.saucelive.net/broadcast/9897?sessionKey=3N0JMQP8z3dB/vwaLUV6nXIrX70dBDOTAUedIrNr+YG0KqpTVmCgKFXngS0Z09P8UEVgjQeQIjXXpOloF09CurpNStsPHOSLd7RCsh2WggjLWhc2664QxMTULpnA/l+0bl/+2QZIeJATz5rKp9CorLu/wwxtvnwhzdAyxDdu6zSOMPO2tyM5Yyn36JkEiott&serviceId=skmagic    
    
  - image: https://img.youtube.com/vi/azu5oR1m62Q/hqdefault.jpg
    link: https://youtu.be/azu5oR1m62Q
    
  - image: https://img.youtube.com/vi/YVhaikslh28/hqdefault.jpg
    link: https://youtu.be/YVhaikslh28
    
  - image: https://img.youtube.com/vi/372yRcG-Sa4/hqdefault.jpg
    link: https://youtu.be/372yRcG-Sa4
    
  - image: https://img.youtube.com/vi/P5tK8f3jKQs/hqdefault.jpg
    link: https://youtu.be/P5tK8f3jKQs
sass:
  style: compressed
  load_paths:
    - _sass
